### ISSUE TITLE
サーバが"error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)"で落ちるときがある。

### ISSUE THREAD

**Issue by kamekyame** [codeforkosen/Kakomimasu#128]
#127 にてwsモジュール内でUncaught例外が落ちるのは改善されたが、次はservest内で落ちてしまうらしい。
```
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
      await Deno.writeAll(
      ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
    at async BufWriter.flush (https://deno.land/std@0.85.0/io/bufio.ts:468:7)
    at async writeFrame (https://deno.land/std@0.85.0/ws/mod.ts:144:3)
```

**Comment by kamekyame** [comment]
同じ例外の種類で違う経路からの例外！？
```
Apr 02 14:49:26 160-251-50-160 deno[47729]: error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
Apr 02 14:49:26 160-251-50-160 deno[47729]:     at handleError (deno:core/core.js:186:12)
Apr 02 14:49:26 160-251-50-160 deno[47729]:     at binOpParseResult (deno:core/core.js:299:32)
Apr 02 14:49:26 160-251-50-160 deno[47729]:     at asyncHandle (deno:core/core.js:223:40)
Apr 02 14:49:26 160-251-50-160 deno[47729]:     at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
Apr 02 14:49:26 160-251-50-160 deno[47729]:     at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```
