### ISSUE TITLE
サーバがerror: Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)で落ちる

### ISSUE THREAD

**Issue by kamekyame** [codeforkosen/Kakomimasu#149]
journalctl で出力したエラーはこのようになった。
再現性はないです
```
Apr 02 14:43:03 160-251-50-160 deno[45699]: error: Uncaught (in promise) ConnectionReset: Connection reset by peer (os error 104)
Apr 02 14:43:03 160-251-50-160 deno[45699]:     at handleError (deno:core/core.js:186:12)
Apr 02 14:43:03 160-251-50-160 deno[45699]:     at binOpParseResult (deno:core/core.js:299:32)
Apr 02 14:43:03 160-251-50-160 deno[45699]:     at asyncHandle (deno:core/core.js:223:40)
Apr 02 14:43:03 160-251-50-160 deno[45699]:     at Array.asyncHandlers.<computed> (deno:core/core.js:238:9)
Apr 02 14:43:03 160-251-50-160 deno[45699]:     at handleAsyncMsgFromRust (deno:core/core.js:207:32)
```

**Comment by kamekyame** [comment]
fix #253
